### PR TITLE
Add support for managing Aphlict

### PR DESCRIPTION
**Pull request by joshuaspence**
Adds support for managing [Aphlict](https://secure.phabricator.com/book/phabricator/article/notifications/).

---
This change is [Reviewable](https://reviewable.io/reviews/joshuaspence/puppet-phabricator/3)

### CODE REVIEW

**Comment by jarro2783** [comment]
Are you amending and force pushing? Not sure if that's messing with the commit history here.

---

Reviewed 12 of 13 files at r1.
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[manifests/aphlict.pp, line 78 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/3#-KkwivgibQxMqxjjA9kj:-KkwivgibQxMqxjjA9kk:b-8d13r2) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/b7d6199013ce0b880c952d42025e1575fd335e91/manifests/aphlict.pp#L78)):*
> ```Puppet
>   # lint:endignore
> 
>   # TODO: Should we also specify `hasrestart => true`? According to the
> ```

We probably could but I guess it's not a major thing. It would be more important if we set the restart command to be a reload.

---

*[spec/acceptance/daemons_spec.rb, line 15 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/3#-KkweA7A9_9LzmvoqqTO:-KkweA7BrZPCKCGWju8D:b4tzk33) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/b7d6199013ce0b880c952d42025e1575fd335e91/spec/acceptance/daemons_spec.rb#L15)):*
> ```Ruby
>     # Ensure that `apt-get update` is executed before any packages are
>     # installed. See https://github.com/puppetlabs/puppetlabs-apt/#adding-new-sources-or-ppas.
>     Class['apt::update'] -> Package <| title != 'apt-transport-https' and title != 'ca-certificates' and title != 'software-properties-common' |>
> ```

I was going to ask why this was commented out earlier, but it looks like now it isn't.

---

*[spec/acceptance/daemons_spec.rb, line 86 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/3#-KkweeiYZ5nXltDD9rqQ:-KkwebQp7eYeRTxqXuJh:b-1xj8mv) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/5e10d7cc61c5b0cc1795a516c817bf3fa9456212/spec/acceptance/daemons_spec.rb#L86)):*
>   context process('php ./phd-daemon') do
>     it { is_expected.to be_running }
>  
>     its(:count) { is_expected.to eq(1) }
>     its(:group) { is_expected.to eq('phabricator') }
>   
Why are you discarding this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/3#-:-Kkwj4Wsm3vSB8sbho7I:b-ypo90c)*

**Comment by joshuaspence** [comment]
Ah yeah. My normal workflow is along the lines of `git commit --amend && git push --force`. I'll try to resist the urge to do that.

**Comment by joshuaspence** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[spec/acceptance/daemons_spec.rb, line 86 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/3#-KkweeiYZ5nXltDD9rqQ:-Kkwxx1mOpz3YKUURWMG:b-rrr6zq) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/5e10d7cc61c5b0cc1795a516c817bf3fa9456212/spec/acceptance/daemons_spec.rb#L86)):*
<details><summary><i>Previously, jarro2783 wrote…</i></summary><blockquote>

>   context process('php ./phd-daemon') do
>     it { is_expected.to be_running }
>  
>     its(:count) { is_expected.to eq(1) }
>     its(:group) { is_expected.to eq('phabricator') }
>   
Why are you discarding this?
</blockquote></details>

It doesn't seem to work. Specifically, it said that the process was running as the `aphlict` user. I think that it's only checking the executable rather than the arguments, so really this code is checking the first `php` process

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/3)*

**Comment by jarro2783** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/3#-:-KkwzrLMiMTL8T2PT42_:bnfp4nl)*

**Pull request merged**
