### PR TITLE
Add ability to run a single daemon

### PR DESCRIPTION
**Pull request by jarro2783**
This adds the ability to run a single daemon for the `phd` service instead of running `phd start`.

---
This change is [Reviewable](https://reviewable.io/reviews/joshuaspence/puppet-phabricator/5)

### CODE REVIEW

**Comment by joshuaspence** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[manifests/daemons.pp, line 40 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1G5I9WhTDZGp9veza:-Kl1G5IASiXLPaXbz3DZ:bx5v7j4) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/9ec665cafa80e7e271b2e4343f94f400fa18a33c/manifests/daemons.pp#L40)):*
> ```Puppet
>   }
> 
>   if $phabricator::run_daemon {
> ```

I feel like maybe this conditional should live in the EPP template?

---

*[manifests/init.pp, line 46 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1GGfWI2Q67qONqKHq:-Kl1GGfWI2Q67qONqKHr:bdag7ak) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/9ec665cafa80e7e271b2e4343f94f400fa18a33c/manifests/init.pp#L46)):*
> ```Puppet
>   Phabricator::Revision $phabricator_revision,
>   Hash[String, Data] $config_hash,
>   Optional[String] $run_daemon,
> ```

I think this should be moved to the `phabricator::daemon` class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Comment by jarro2783** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[manifests/daemons.pp, line 40 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1G5I9WhTDZGp9veza:-Kl1_zi4OUz0lbvfpLPc:b-896fix) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/9ec665cafa80e7e271b2e4343f94f400fa18a33c/manifests/daemons.pp#L40)):*
<details><summary><i>Previously, joshuaspence (Joshua Spence) wrote…</i></summary><blockquote>

I feel like maybe this conditional should live in the EPP template?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Comment by joshuaspence** [comment]
*[manifests/daemons.pp, line 24 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1eoJoc4n3zeKnkVyk:-Kl1eoJoc4n3zeKnkVyl:by6m249) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/4b80a1b0f13685760c33d645a47d683af8f22177/manifests/daemons.pp#L24)):*
> ```Puppet
> # @param run_daemon A single daemon to run instead of the default daemons.
> class phabricator::daemons(
>   Optional[String] $run_daemon = undef,
> ```

You don't need to set `undef` here because it is set as the default value in Hiera.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Comment by joshuaspence** [comment]
*[manifests/daemons.pp, line 23 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1ex1WDo-bmRQlIsqE:-Kl1ex1WDo-bmRQlIsqF:bq8f7qc) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/4b80a1b0f13685760c33d645a47d683af8f22177/manifests/daemons.pp#L23)):*
> ```Puppet
> #
> # @param run_daemon A single daemon to run instead of the default daemons.
> class phabricator::daemons(
> ```

Add an empty comment between the comment block and the code. i.e.

```
# @param ...
#
class phabricator::daemons(
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Comment by joshuaspence** [comment]
*[manifests/daemons.pp, line 24 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1f4rYQUCfaqzjmLnm:-Kl1f4rYQUCfaqzjmLnn:bmgdeoe) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/4b80a1b0f13685760c33d645a47d683af8f22177/manifests/daemons.pp#L24)):*
> ```Puppet
> # @param run_daemon A single daemon to run instead of the default daemons.
> class phabricator::daemons(
>   Optional[String] $run_daemon = undef,
> ```

I think we should call this `$launch_daemon` rather than `$run_daemon`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Comment by joshuaspence** [comment]
*[manifests/daemons.pp, line 24 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1f4rYQUCfaqzjmLnm:-Kl1fH8U_HEczhobx8c4:b-29219y) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/4b80a1b0f13685760c33d645a47d683af8f22177/manifests/daemons.pp#L24)):*
<details><summary><i>Previously, joshuaspence (Joshua Spence) wrote…</i></summary><blockquote>

I think we should call this `$launch_daemon` rather than `$run_daemon`
</blockquote></details>

Actually, how about jus t`$daemon` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Comment by joshuaspence** [comment]
*[spec/classes/daemons_spec.rb, line 84 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1fMFpvY49u4tOMlvW:-Kl1fMFpvY49u4tOMlvX:bruiwds) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/4b80a1b0f13685760c33d645a47d683af8f22177/spec/classes/daemons_spec.rb#L84)):*
> ```Ruby
>         let(:params) do
>           {
>             run_daemon: 'repo_pull',
> ```

I don't think this actually works (in that it won't run the repo pull daemon in an acceptance test) because `repo_pull` is not a substring of `PhabricatorRepositoryPullDaemon`. So maybe change this to just `repo`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Comment by jarro2783** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[manifests/daemons.pp, line 23 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1ex1WDo-bmRQlIsqE:-Kl1gB10Pt70hV0qtNHD:b-896fix) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/4b80a1b0f13685760c33d645a47d683af8f22177/manifests/daemons.pp#L23)):*
<details><summary><i>Previously, joshuaspence (Joshua Spence) wrote…</i></summary><blockquote>

Add an empty comment between the comment block and the code. i.e.

```
# @param ...
#
class phabricator::daemons(
```
</blockquote></details>

Done.

---

*[manifests/daemons.pp, line 24 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1eoJoc4n3zeKnkVyk:-Kl1gBQ6O1V-1VKoWkd4:b-896fix) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/4b80a1b0f13685760c33d645a47d683af8f22177/manifests/daemons.pp#L24)):*
<details><summary><i>Previously, joshuaspence (Joshua Spence) wrote…</i></summary><blockquote>

You don't need to set `undef` here because it is set as the default value in Hiera.
</blockquote></details>

Done.

---

*[manifests/daemons.pp, line 24 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1f4rYQUCfaqzjmLnm:-Kl1gBhL_5KCFce67g4G:b-896fix) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/4b80a1b0f13685760c33d645a47d683af8f22177/manifests/daemons.pp#L24)):*
<details><summary><i>Previously, joshuaspence (Joshua Spence) wrote…</i></summary><blockquote>

Actually, how about jus t`$daemon` instead?
</blockquote></details>

Done.

---

*[spec/classes/daemons_spec.rb, line 84 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1fMFpvY49u4tOMlvW:-Kl1gCYCkWCW_SxU-lhL:b-896fix) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/4b80a1b0f13685760c33d645a47d683af8f22177/spec/classes/daemons_spec.rb#L84)):*
<details><summary><i>Previously, joshuaspence (Joshua Spence) wrote…</i></summary><blockquote>

I don't think this actually works (in that it won't run the repo pull daemon in an acceptance test) because `repo_pull` is not a substring of `PhabricatorRepositoryPullDaemon`. So maybe change this to just `repo`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Comment by joshuaspence** [comment]
*[manifests/daemons.pp, line 54 at r3](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1gbw75WTHuBZWHfsw:-Kl1gbw75WTHuBZWHfsx:b-qhfklp) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/5e676dd0f83e4d47eb365781501cb67d2fb6356d/manifests/daemons.pp#L54)):*
> ```Puppet
>       user          => $phabricator::daemon_user,
>       group         => $phabricator::group,
>       start_command => $daemon,
> ```

I think you should rename `start_command` to `daemon`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Comment by joshuaspence** [comment]
*[spec/classes/daemons_spec.rb, line 81 at r3](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1ghVMZt6BX2C3a8ln:-Kl1ghVMZt6BX2C3a8lo:b-8niv7q) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/5e676dd0f83e4d47eb365781501cb67d2fb6356d/spec/classes/daemons_spec.rb#L81)):*
> ```Ruby
>       end
> 
>       context 'when $run_daemon is set' do
> ```

The parameter name needs to be updated here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Comment by joshuaspence** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-:-Kl1gxRTnBFhpKeLH_we:bnfp4nl)*

**Comment by jarro2783** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[manifests/daemons.pp, line 24 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1f4rYQUCfaqzjmLnm:-Kl1jOfAPgoIYfrYiGxW:b-896fix) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/4b80a1b0f13685760c33d645a47d683af8f22177/manifests/daemons.pp#L24)):*
<details><summary><i>Previously, jarro2783 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[manifests/daemons.pp, line 54 at r3](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1gbw75WTHuBZWHfsw:-Kl1jTnsmtiFGV10yDOz:b-896fix) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/5e676dd0f83e4d47eb365781501cb67d2fb6356d/manifests/daemons.pp#L54)):*
<details><summary><i>Previously, joshuaspence (Joshua Spence) wrote…</i></summary><blockquote>

I think you should rename `start_command` to `daemon`
</blockquote></details>

Done.

---

*[spec/classes/daemons_spec.rb, line 81 at r3](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5#-Kl1ghVMZt6BX2C3a8ln:-Kl1jdXgotiilFro9vTW:b-896fix) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/5e676dd0f83e4d47eb365781501cb67d2fb6356d/spec/classes/daemons_spec.rb#L81)):*
<details><summary><i>Previously, joshuaspence (Joshua Spence) wrote…</i></summary><blockquote>

The parameter name needs to be updated here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/5)*

**Pull request merged**
