### PR TITLE
Add support for registering an Almanac device

### PR DESCRIPTION
**Pull request by joshuaspence**
Adds support for registering an Almanac device.

---
This change is [Reviewable](https://reviewable.io/reviews/joshuaspence/puppet-phabricator/4)

### CODE REVIEW

**Comment by jarro2783** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[manifests/init.pp, line 86 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/4#-Kl0tOkvVlfPJhFSnWX4:-Kl0tOkvVlfPJhFSnWX5:buuv6n7) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/9a861d3866acf528e0bcff2274458a84eb0ab396/manifests/init.pp#L86)):*
> ```Puppet
>   include phabricator::install
> 
>   if $register_almanac_device {
> ```

Should this be left up to the user? They need to set the parameters anyway, so why not just let the user include `phabricator::almanac` too?

---

*[spec/acceptance/almanac_spec.rb, line 56 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/4#-Kl0tj0LyL9-qU-4Y8lO:-Kl0tj0LyL9-qU-4Y8lP:b8aoiow) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/9a861d3866acf528e0bcff2274458a84eb0ab396/spec/acceptance/almanac_spec.rb#L56)):*
> ```Ruby
> 
>   it 'applies with no errors' do
>     apply_manifest(pp, catch_failures: false)
> ```

I'm guessing this will fail saying that the key doesn't exist. Is there much value in putting this here given that it will fail travis forever?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/4)*

**Comment by joshuaspence** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[spec/acceptance/almanac_spec.rb, line 56 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/4#-Kl0tj0LyL9-qU-4Y8lO:-Kl0wNrvYlbmzkPNhBJo:b-un2y53) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/9a861d3866acf528e0bcff2274458a84eb0ab396/spec/acceptance/almanac_spec.rb#L56)):*
<details><summary><i>Previously, jarro2783 wrote…</i></summary><blockquote>

I'm guessing this will fail saying that the key doesn't exist. Is there much value in putting this here given that it will fail travis forever?
</blockquote></details>

Really I just wanted to leave a comment to remind myself to write tests... I guess I should just remove `apply_manifest`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/4)*

**Comment by joshuaspence** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[spec/acceptance/almanac_spec.rb, line 56 at r1](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/4#-Kl0tj0LyL9-qU-4Y8lO:-Kl0wv6ZOwbK7bMGT9Fb:b-mvct96) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/9a861d3866acf528e0bcff2274458a84eb0ab396/spec/acceptance/almanac_spec.rb#L56)):*
<details><summary><i>Previously, joshuaspence (Joshua Spence) wrote…</i></summary><blockquote>

Really I just wanted to leave a comment to remind myself to write tests... I guess I should just remove `apply_manifest`
</blockquote></details>

Although, currently I am testing the `device.key` file, so maybe there is some value here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/4)*

**Comment by jarro2783** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[manifests/almanac.pp, line 18 at r2](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/4#-Kl12DlShCf_zee_g_l1:-Kl12DlTwVX228zdaxzn:b-r8n2oz) ([raw file](https://github.com/joshuaspence/puppet-phabricator/blob/feadc6703a971e9faaf63f223622cc6d7eb87bc0/manifests/almanac.pp#L18)):*
> ```Puppet
>     owner   => $phabricator::daemon_user,
>     group   => 'root',
>     mode    => '0400',
> ```

There's the test failure, the mode is wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/4)*

**Comment by jarro2783** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/joshuaspence/puppet-phabricator/4#-:-Kl1DEYf5lhMVUYzbfVA:bnfp4nl)*

**Comment by joshuaspence** [comment]
I believe the test failures are unrelated as I've something similar previously. I'll try to fix that separately.

```
root@ubuntu-16:~# /usr/local/src/phabricator/bin/phd status --local
There are no running Phabricator daemons.
root@ubuntu-16:~# /usr/local/src/phabricator/bin/phd status
Log Daemon       Host      Overseer Started                  Class                                Arguments
3   16804:37ie7p ubuntu-16 16804    May 26 2017, 12:32:05 AM PhabricatorTaskmasterDaemon          
2   16804:uh7blo ubuntu-16 16804    May 26 2017, 12:32:05 AM PhabricatorTriggerDaemon             
1   16804:2gtkrc ubuntu-16 16804    May 26 2017, 12:32:05 AM PhabricatorRepositoryPullLocalDaemon
```

**Pull request merged**
